# Site settings
title: LiuXin21 #website title
description: > # this means to ignore newlines until "baseurl:"
  LiuXin21
url: #https://kuoa.github.io # the base hostname & protocol for your site
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Home
    url:          /
  - name:         计算流体力学CFD
    url:          /导航navigation/计算流体力学CFD
    external:     false
  - name:         编程programing
    url:          /导航navigation/编程programing
    external:     false
  - name:         软件software
    url:          /导航navigation/软件software
    external:     false
  - name:         关于About
    url:          /导航navigation/关于about
    external:     false
  - name:         存档Archive
    url:          /导航navigation/存档archive
    external:     false
#  - name:         Web
#    url:          www.liuxin.in
#    external:     true

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]